In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("student_placement_anxiety_dataset.csv")

In [3]:
df.head()

,Student_ID,Branch,CGPA,Internships,Mock_Test_Score,Coding_Hours_Per_Week,Resume_Score,Anxiety_Level,Expected_Package_LPA,Placement_Status
0,S001,IT,8.24,0,92,11,65,Low,11.8,Placed
1,S002,CSE,8.37,4,50,21,77,Low,5.6,Placed
2,S003,IT,7.77,0,80,9,95,High,8.4,Not Placed
3,S004,ECE,6.97,0,55,25,77,High,6.3,Not Placed
4,S005,CSE,6.75,2,51,5,74,High,7.3,Not Placed

In [4]:
df.shape

(100, 10)

In [5]:
df.columns

Index(['Student_ID', 'Branch', 'CGPA', 'Internships', 'Mock_Test_Score',
       'Coding_Hours_Per_Week', 'Resume_Score', 'Anxiety_Level',
       'Expected_Package_LPA', 'Placement_Status'],
      dtype='object')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Student_ID             100 non-null    object
 1   Branch                 100 non-null    object
 2   CGPA                   100 non-null    float64
 3   Internships            100 non-null    int64
 4   Mock_Test_Score        100 non-null    int64
 5   Coding_Hours_Per_Week  100 non-null    int64
 6   Resume_Score           100 non-null    int64
 7   Anxiety_Level          100 non-null    object
 8   Expected_Package_LPA   100 non-null    float64
 9   Placement_Status       100 non-null    object
dtypes: float64(2), int64(4), object(4)
memory usage: 7.9+ KB

In [7]:
df2 = pd.read_csv("student_performance.csv")

In [8]:
df2.head()

,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,18.5,95.6,3.8,97.9,A
1,2,14.0,80.0,2.5,83.9,B
2,3,19.5,86.3,5.3,100.0,A
3,4,25.7,70.2,7.0,100.0,A
4,5,13.4,81.9,6.9,92.0,A

In [9]:
df2.columns

Index(['student_id', 'weekly_self_study_hours', 'attendance_percentage',
       'class_participation', 'total_score', 'grade'],
      dtype='object')

In [10]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 6 columns):
 #   Column                   Non-Null Count    Dtype
---  ------                   --------------    -----
 0   student_id               1000000 non-null  int64
 1   weekly_self_study_hours  1000000 non-null  float64
 2   attendance_percentage    1000000 non-null  float64
 3   class_participation      1000000 non-null  float64
 4   total_score              1000000 non-null  float64
 5   grade                    1000000 non-null  object
dtypes: float64(4), int64(1), object(1)
memory usage: 45.8+ MB

In [11]:
df2.shape

(1000000, 6)

In [16]:
df2 = df2.rename(columns={"student id": "Student_ID"})

In [17]:
df["Student_ID"] = df["Student_ID"].astype(str).str.replace("S","", regex=False).astype(int)

In [54]:
merged_df = pd.merge(df, df2, 
                     left_on="Student_ID", 
                     right_on="student_id")

In [19]:
merged_df.shape

(100, 16)

In [20]:
merged_df.head()

,Student_ID,Branch,CGPA,Internships,Mock_Test_Score,Coding_Hours_Per_Week,Resume_Score,Anxiety_Level,Expected_Package_LPA,Placement_Status,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,1,IT,8.24,0,92,11,65,Low,11.8,Placed,1,18.5,95.6,3.8,97.9,A
1,2,CSE,8.37,4,50,21,77,Low,5.6,Placed,2,14.0,80.0,2.5,83.9,B
2,3,IT,7.77,0,80,9,95,High,8.4,Not Placed,3,19.5,86.3,5.3,100.0,A
3,4,ECE,6.97,0,55,25,77,High,6.3,Not Placed,4,25.7,70.2,7.0,100.0,A
4,5,CSE,6.75,2,51,5,74,High,7.3,Not Placed,5,13.4,81.9,6.9,92.0,A

In [21]:
merged_df.columns

Index(['Student_ID', 'Branch', 'CGPA', 'Internships', 'Mock_Test_Score',
       'Coding_Hours_Per_Week', 'Resume_Score', 'Anxiety_Level',
       'Expected_Package_LPA', 'Placement_Status', 'student_id',
       'weekly_self_study_hours', 'attendance_percentage',
       'class_participation', 'total_score', 'grade'],
      dtype='object')

In [22]:
merged_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 16 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Student_ID               100 non-null    int64
 1   Branch                   100 non-null    object
 2   CGPA                     100 non-null    float64
 3   Internships              100 non-null    int64
 4   Mock_Test_Score          100 non-null    int64
 5   Coding_Hours_Per_Week    100 non-null    int64
 6   Resume_Score             100 non-null    int64
 7   Anxiety_Level            100 non-null    object
 8   Expected_Package_LPA     100 non-null    float64
 9   Placement_Status         100 non-null    object
 10  student_id               100 non-null    int64
 11  weekly_self_study_hours  100 non-null    float64
 12  attendance_percentage    100 non-null    float64
 13  class_participation      100 non-null    float64
 14  total_score              100 non-null    float64
 15  grade                    100 non-null    object
dtypes: float64(6), int64(6), object(4)
memory usage: 12.6+ KB

In [23]:
merged_df.isnull()

,Student_ID,Branch,CGPA,Internships,Mock_Test_Score,Coding_Hours_Per_Week,Resume_Score,Anxiety_Level,Expected_Package_LPA,Placement_Status,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score,grade
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
96,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
97,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
98,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
99,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [24]:
merged_df.isnull().sum()

Student_ID                 0
Branch                     0
CGPA                       0
Internships                0
Mock_Test_Score            0
Coding_Hours_Per_Week      0
Resume_Score               0
Anxiety_Level              0
Expected_Package_LPA       0
Placement_Status           0
student_id                 0
weekly_self_study_hours    0
attendance_percentage      0
class_participation        0
total_score                0
grade                      0
dtype: int64

In [25]:
merged_df.describe()

,Student_ID,CGPA,Internships,Mock_Test_Score,Coding_Hours_Per_Week,Resume_Score,Expected_Package_LPA,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score
count,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000,100.000000
mean,50.500000,7.705100,1.860000,67.53000,13.260000,74.550000,8.85600,50.500000,14.312000,83.872000,6.047000,82.689000
std,29.011492,1.004176,1.333485,13.74549,6.568397,12.808122,3.30776,29.011492,6.274033,8.867647,1.799352,15.378536
min,1.000000,6.020000,0.000000,45.00000,3.000000,50.000000,3.30000,1.000000,0.000000,64.400000,2.500000,47.400000
25%,25.750000,6.947500,1.000000,57.00000,7.000000,64.750000,5.97500,25.750000,10.800000,78.275000,4.600000,70.725000
50%,50.500000,7.770000,2.000000,67.00000,12.000000,77.500000,8.55000,50.500000,14.100000,83.800000,6.000000,83.950000
75%,75.250000,8.510000,3.000000,78.25000,18.250000,85.000000,11.45000,75.250000,17.825000,90.150000,7.600000,97.600000
max,100.000000,9.500000,4.000000,92.00000,25.000000,95.000000,14.40000,100.000000,28.000000,100.000000,9.700000,100.000000

In [26]:
df3=pd.read_csv("Math-Students.csv")

In [27]:
df3.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [28]:
df3.columns

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [29]:
df3.shape

(399, 33)

In [30]:
df3.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 399 entries, 0 to 398
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      399 non-null    object
 1   sex         399 non-null    object
 2   age         399 non-null    int64
 3   address     399 non-null    object
 4   famsize     399 non-null    object
 5   Pstatus     399 non-null    object
 6   Medu        399 non-null    int64
 7   Fedu        399 non-null    int64
 8   Mjob        399 non-null    object
 9   Fjob        399 non-null    object
 10  reason      399 non-null    object
 11  guardian    399 non-null    object
 12  traveltime  399 non-null    int64
 13  studytime   399 non-null    int64
 14  failures    399 non-null    int64
 15  schoolsup   399 non-null    object
 16  famsup      399 non-null    object
 17  paid        399 non-null    object
 18  activities  399 non-null    object
 19  nursery     399 non-null    object
 20  higher      399 non-null    object
 21  internet    399 non-null    object
 22  romantic    399 non-null    object
 23  famrel      399 non-null    int64
 24  freetime    399 non-null    int64
 25  goout       399 non-null    int64
 26  Dalc        399 non-null    int64
 27  Walc        399 non-null    int64
 28  health      399 non-null    int64
 29  absences    399 non-null    int64
 30  G1          399 non-null    int64
 31  G2          399 non-null    int64
 32  G3          399 non-null    int64
dtypes: int64(16), object(17)
memory usage: 103.0+ KB

In [31]:
df3.isnull().sum()

school        0
sex           0
age           0
address       0
famsize       0
Pstatus       0
Medu          0
Fedu          0
Mjob          0
Fjob          0
reason        0
guardian      0
traveltime    0
studytime     0
failures      0
schoolsup     0
famsup        0
paid          0
activities    0
nursery       0
higher        0
internet      0
romantic      0
famrel        0
freetime      0
goout         0
Dalc          0
Walc          0
health        0
absences      0
G1            0
G2            0
G3            0
dtype: int64

In [32]:
df3.describe()

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000
mean,16.709273,2.761905,2.536341,1.443609,2.035088,0.330827,3.954887,3.233083,3.097744,1.476190,2.288221,3.558897,5.651629,10.879699,10.676692,10.380952
std,1.278225,1.096340,1.092716,0.695429,0.835020,0.740655,0.898335,0.994107,1.113178,0.887552,1.281737,1.384013,7.983113,3.315195,3.760845,4.571073
min,15.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,16.000000,2.000000,2.000000,1.000000,1.000000,0.000000,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,8.500000,8.000000
50%,17.000000,3.000000,3.000000,1.000000,2.000000,0.000000,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,18.000000,4.000000,3.500000,2.000000,2.000000,0.000000,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,13.500000
max,22.000000,4.000000,4.000000,4.000000,4.000000,3.000000,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [33]:
df3.describe(include='all')

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
count,399,399,399.000000,399,399,399,399.000000,399.000000,399,399,...,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000,399.000000
unique,2,2,NaN,2,2,2,NaN,NaN,5,5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,GP,F,NaN,U,GT3,T,NaN,NaN,other,other,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,349,208,NaN,311,285,358,NaN,NaN,141,218,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,16.709273,NaN,NaN,NaN,2.761905,2.536341,NaN,NaN,...,3.954887,3.233083,3.097744,1.476190,2.288221,3.558897,5.651629,10.879699,10.676692,10.380952
std,NaN,NaN,1.278225,NaN,NaN,NaN,1.096340,1.092716,NaN,NaN,...,0.898335,0.994107,1.113178,0.887552,1.281737,1.384013,7.983113,3.315195,3.760845,4.571073
min,NaN,NaN,15.000000,NaN,NaN,NaN,0.000000,0.000000,NaN,NaN,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,3.000000,0.000000,0.000000
25%,NaN,NaN,16.000000,NaN,NaN,NaN,2.000000,2.000000,NaN,NaN,...,4.000000,3.000000,2.000000,1.000000,1.000000,3.000000,0.000000,8.000000,8.500000,8.000000
50%,NaN,NaN,17.000000,NaN,NaN,NaN,3.000000,3.000000,NaN,NaN,...,4.000000,3.000000,3.000000,1.000000,2.000000,4.000000,4.000000,11.000000,11.000000,11.000000
75%,NaN,NaN,18.000000,NaN,NaN,NaN,4.000000,3.500000,NaN,NaN,...,5.000000,4.000000,4.000000,2.000000,3.000000,5.000000,8.000000,13.000000,13.000000,13.500000
max,NaN,NaN,22.000000,NaN,NaN,NaN,4.000000,4.000000,NaN,NaN,...,5.000000,5.000000,5.000000,5.000000,5.000000,5.000000,75.000000,19.000000,19.000000,20.000000

In [34]:
df3['sex'].value_counts()

sex
F    208
M    191
Name: count, dtype: int64

df3['school'].value_counts()

In [35]:
df3['school'].value_counts()

school
GP    349
MS     50
Name: count, dtype: int64

In [36]:
df3['famsize'].value_counts()

famsize
GT3    285
LE3    114
Name: count, dtype: int64

In [37]:

df3['Mjob'].value_counts()

Mjob
other       141
services    103
teacher      62
at_home      59
health       34
Name: count, dtype: int64

In [38]:

df3['Fjob'].value_counts()

Fjob
other       218
services    113
teacher      29
at_home      21
health       18
Name: count, dtype: int64

In [39]:
df3['Pstatus'].value_counts()

Pstatus
T    358
A     41
Name: count, dtype: int64

In [40]:
df3[['age', 'Medu', 'Fedu']].describe()

              age        Medu        Fedu
count  399.000000  399.000000  399.000000
mean    16.709273    2.761905    2.536341
std      1.278225    1.096340    1.092716
min     15.000000    0.000000    0.000000
25%     16.000000    2.000000    2.000000
50%     17.000000    3.000000    3.000000
75%     18.000000    4.000000    3.500000
max     22.000000    4.000000    4.000000

In [41]:
df3['age'].value_counts()

age
16    104
17     99
18     84
15     82
19     25
20      3
22      1
21      1
Name: count, dtype: int64

In [42]:
df3['Medu'].value_counts()

Medu
4    135
2    103
3     99
1     59
0      3
Name: count, dtype: int64

In [45]:
df3['Fedu'].value_counts()

Fedu
2    115
4    100
3    100
1     82
0      2
Name: count, dtype: int64

In [46]:
merged_df["Placement_Status"].value_counts()

Placement_Status
Not Placed    57
Placed        43
Name: count, dtype: int64

In [47]:
merged_df.groupby("Placement_Status")["CGPA"].mean()

Placement_Status
Not Placed    7.218070
Placed        8.350698
Name: CGPA, dtype: float64

In [48]:
merged_df.groupby("Placement_Status")["Internships"].mean()

Placement_Status
Not Placed    1.824561
Placed        1.906977
Name: Internships, dtype: float64

In [49]:
merged_df.corr(numeric_only=True)

,Student_ID,CGPA,Internships,Mock_Test_Score,Coding_Hours_Per_Week,Resume_Score,Expected_Package_LPA,student_id,weekly_self_study_hours,attendance_percentage,class_participation,total_score
Student_ID,1.000000,-0.139233,0.024543,0.071874,-0.088681,0.017085,-0.121848,1.000000,0.049390,-0.092810,0.039213,0.033653
CGPA,-0.139233,1.000000,-0.085079,0.107685,-0.105090,0.032349,-0.011187,-0.139233,0.141393,0.102161,0.031837,0.058099
Internships,0.024543,-0.085079,1.000000,0.032745,0.164497,0.131116,0.065000,0.024543,-0.199612,-0.072089,0.068022,-0.188826
Mock_Test_Score,0.071874,0.107685,0.032745,1.000000,-0.076500,-0.039368,0.123041,0.071874,-0.033877,0.223830,-0.007838,-0.064071
Coding_Hours_Per_Week,-0.088681,-0.105090,0.164497,-0.076500,1.000000,-0.097770,-0.023225,-0.088681,0.099438,-0.054466,0.164331,0.131706
Resume_Score,0.017085,0.032349,0.131116,-0.039368,-0.097770,1.000000,0.105053,0.017085,-0.179833,-0.083026,-0.029359,-0.182784
Expected_Package_LPA,-0.121848,-0.011187,0.065000,0.123041,-0.023225,0.105053,1.000000,-0.121848,-0.023220,-0.091548,0.036788,-0.020133
student_id,1.000000,-0.139233,0.024543,0.071874,-0.088681,0.017085,-0.121848,1.000000,0.049390,-0.092810,0.039213,0.033653
weekly_self_study_hours,0.049390,0.141393,-0.199612,-0.033877,0.099438,-0.179833,-0.023220,0.049390,1.000000,-0.028716,0.134064,0.817997
attendance_percentage,-0.092810,0.102161,-0.072089,0.223830,-0.054466,-0.083026,-0.091548,-0.092810,-0.028716,1.000000,0.040276,-0.059893
class_participation,0.039213,0.031837,0.068022,-0.007838,0.164331,-0.029359,0.036788,0.039213,0.134064,0.040276,1.000000,0.002844
total_score,0.033653,0.058099,-0.188826,-0.064071,0.131706,-0.182784,-0.020133,0.033653,0.817997,-0.059893,0.002844,1.000000

In [50]:
merged_df.to_csv("final_placement_dataset.csv", index=False)